<a href="https://colab.research.google.com/github/leonardoleandrodev/aprendizadodemaquina01/blob/main/test_sequencial_ok.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from numpy import loadtxt
import numpy as np
from keras.models import Sequential
from sklearn.naive_bayes import MultinomialNB
from keras.layers import Dense
from pandas import read_csv as rc,factorize as fc,to_numeric as tnum,set_option as op

In [3]:
def getUniqueNumber(seq):
    s = 0
    for i,q in enumerate(seq):
      s+=(q**(q+i))
    return s

In [4]:
from random import randint as ri
data=[]
for k in range(1,100000):
  nm = [ri(0,2) for k in range(6)]
  #if not nm in data:
  data.append(nm)

res = []
for d in data:
  res.append(getUniqueNumber(d))

resuniq = np.unique(res)
tamres = len(np.unique(res))
print(data[:10])
print(res[:10])
resuniq

[[0, 1, 2, 2, 2, 0], [0, 0, 2, 2, 1, 2], [2, 0, 1, 1, 0, 0], [0, 1, 1, 0, 1, 2], [2, 1, 1, 2, 0, 2], [2, 1, 2, 0, 2, 1], [0, 1, 1, 1, 0, 0], [2, 2, 0, 1, 0, 0], [1, 0, 1, 1, 1, 0], [0, 0, 1, 1, 1, 1]]
[114, 178, 6, 132, 166, 86, 4, 13, 4, 5]


array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  49,  50,  51,  52,  53,  54,
        55,  57,  58,  59,  60,  61,  62,  65,  66,  67,  68,  69,  70,
        71,  72,  73,  74,  75,  76,  77,  78,  79,  81,  82,  83,  84,
        85,  86,  87,  89,  90,  91,  92,  93,  94,  97,  98,  99, 100,
       101, 102, 103, 105, 106, 107, 108, 109, 110, 113, 114, 115, 116,
       117, 118, 121, 122, 124, 125, 129, 130, 131, 132, 133, 134, 135,
       136, 137, 138, 139, 140, 141, 142, 143, 145, 146, 147, 148, 149,
       150, 151, 153, 154, 155, 156, 157, 158, 161, 162, 163, 164, 165,
       166, 167, 169, 170, 171, 172, 173, 174, 177, 178, 179, 180, 181,
       182, 185, 186, 188, 189, 193, 194, 195, 196, 197, 198, 199, 201,
       202, 203, 204, 205, 206, 209, 210, 211, 212, 213, 214, 21

In [5]:
from sklearn.model_selection import train_test_split
val_treino,val_teste,val_res_treino,val_res_teste = train_test_split(data,res,test_size=0.1,train_size=0.5)

#val_treino = np.array(val_treino)
#val_teste = np.array(val_teste)
#val_res_treino = np.array(val_res_treino)
#val_res_teste = np.array(val_res_teste)


MODELO NOMINAL


In [ ]:
# definir o modelo com keras
model = MultinomialNB()
model.fit(val_treino, val_res_treino)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

Modelo Sequencial SOFTMAX(varias saidas)


In [6]:
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
X = np.array(val_treino)
Y  = np.array(val_res_treino)

def baseline_model():
  # create model
  model = Sequential()
  model.add(Dense(20, input_dim=len(X[0]), activation='relu'))
  model.add(Dense(20,  activation='relu'))
  #model.add(Dense(20,  activation='relu'))
  model.add(Dense(len(resuniq), activation='softmax'))
  # Compile model
  model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
  return model

estimator = KerasClassifier(build_fn=baseline_model, epochs=30, batch_size=10,use_multiprocessing=True, verbose=1)


TREINAMENTO

In [7]:
estimator.fit(X,Y)
#estimator.save('/content/random_seq_len4.h5')

Epoch 1/30
5000/5000 [==============================] - 21s 1ms/step - loss: 2.9637 - accuracy: 0.3089
Epoch 2/30
5000/5000 [==============================] - 7s 1ms/step - loss: 0.6539 - accuracy: 0.8097
Epoch 3/30
5000/5000 [==============================] - 7s 1ms/step - loss: 0.3264 - accuracy: 0.9080
Epoch 4/30
5000/5000 [==============================] - 7s 1ms/step - loss: 0.1782 - accuracy: 0.9527
Epoch 5/30
5000/5000 [==============================] - 7s 1ms/step - loss: 0.1009 - accuracy: 0.9762
Epoch 6/30
5000/5000 [==============================] - 7s 1ms/step - loss: 0.0545 - accuracy: 0.9891
Epoch 7/30
5000/5000 [==============================] - 7s 1ms/step - loss: 0.0347 - accuracy: 0.9936
Epoch 8/30
5000/5000 [==============================] - 7s 1ms/step - loss: 0.0215 - accuracy: 0.9956
Epoch 9/30
5000/5000 [==============================] - 7s 1ms/step - loss: 0.0179 - accuracy: 0.9964
Epoch 10/30
5000/5000 [==============================] - 7s 1ms/step - loss: 0.03

VERIFICA PORCENTAGEM DE ACERTO(ACURÁCIA)

In [8]:
from sklearn.metrics import confusion_matrix,accuracy_score
pred = estimator.predict(val_teste)
accuracy = accuracy_score(val_res_teste, pred)
mt = confusion_matrix(val_res_teste, pred)
print(mt,f'\nacuracia de {accuracy*100} %\n')


/usr/local/lib/python3.7/dist-packages/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


1000/1000 [==============================] - 1s 928us/step
[[ 31   0   0 ...   0   0   0]
 [  0 135   0 ...   0   0   0]
 [  0   0 304 ...   0   0   0]
 ...
 [  0   0   0 ...  17   0   0]
 [  0   0   0 ...   0  32   0]
 [  0   0   0 ...   0   0  14]] 
acuracia de 99.76 %



VERIFICA ACERTOS

In [15]:
import random as rn
nm = rn.randint(1,len(X))
confer = X[nm:nm+10]
confer = [[1,2,2,2,1,2]]
pred = estimator.predict(confer)

for i,prd in enumerate(pred):
  if list(confer[i]) == data[res.index(prd)]:
    print(f'acertou! =D Proc:{list(confer[i])} Encontrado:{data[res.index(prd)]} ValorRes:{getUniqueNumber(data[res.index(prd)])} ValorPred:{getUniqueNumber(confer[i])} Index:{res.index(prd)} Id:{prd}')
  else:
    print(f'errou   =(( Proc:{list(confer[i])} Encontrado:{data[res.index(prd)]} ValorRes:{getUniqueNumber(data[res.index(prd)])} ValorPred:{getUniqueNumber(confer[i])} Index:{res.index(prd)} Id:{prd}')

1/1 [==============================] - 0s 30ms/step
errou   =(( Proc:[1, 2, 2, 2, 1, 2] Encontrado:[0, 2, 2, 2, 1, 2] ValorRes:186 ValorPred:186 Index:74 Id:186


/usr/local/lib/python3.7/dist-packages/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Modelo Sequencial sigmoid


In [ ]:
# definir o modelo com keras
# inicializar o modelo sequencial

#model = MultinomialNB()
model = Sequential()
# inicializar a primeira camada, com 12 neurônios, 8 entradas utilizando a função ReLU
model.add(Dense(5, input_dim=len(val_treino[0]), activation='relu'))
#model.add(Dense(10, activation='relu'))
#model.add(Dense(5, activation='sigmoid'))
# inicializar a última camada (camada de saída) com um neurônio e a função Sigmoid/softmax
model.add(Dense(1, activation='sigmoid'))
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(val_treino, val_res_treino, epochs=100, batch_size=15,use_multiprocessing=False,verbose=1)

Epoch 1/100
1/1 [==============================] - 1s 736ms/step - loss: 19.4849 - accuracy: 0.0000e+00
Epoch 2/100
1/1 [==============================] - 0s 8ms/step - loss: 19.3599 - accuracy: 0.0000e+00
Epoch 3/100
1/1 [==============================] - 0s 8ms/step - loss: 19.2350 - accuracy: 0.0000e+00
Epoch 4/100
1/1 [==============================] - 0s 8ms/step - loss: 19.1102 - accuracy: 0.0000e+00
Epoch 5/100
1/1 [==============================] - 0s 6ms/step - loss: 18.9855 - accuracy: 0.0000e+00
Epoch 6/100
1/1 [==============================] - 0s 6ms/step - loss: 18.8609 - accuracy: 0.0000e+00
Epoch 7/100
1/1 [==============================] - 0s 5ms/step - loss: 18.7365 - accuracy: 0.0000e+00
Epoch 8/100
1/1 [==============================] - 0s 4ms/step - loss: 18.6100 - accuracy: 0.0000e+00
Epoch 9/100
1/1 [==============================] - 0s 5ms/step - loss: 18.4803 - accuracy: 0.0000e+00
Epoch 10/100
1/1 [==============================] - 0s 8ms/step - loss: 18.3506 

In [ ]:

#predictions = model.predict(val_teste)
#from sklearn.metrics import confusion_matrix,accuracy_score
#accuracy = accuracy_score(val_res_teste, predictions)
#mt = confusion_matrix(val_res_teste, predictions)
#print(mt,f'acuracia de {accuracy*100} %')
pred = model.predict([[2,2,2,1]])

#res.index(pred),res[res.index(pred)],data[res.index(pred)],getUniqueNumber(res.index(pred)),pred
pred

array([29])